### ISSUE TITLE
No Travis set up

### ISSUE THREAD

**Issue by willemstuursma** [mediact/dependency-guard#2]
Travis is not set up for this package. 

It should at a bare minimum run the test suite. 

It needs to be enabled on this project, then it works for PRs too. 

For bonus points, dependecy-guard should run on itself :)

**Comment by johmanx10** [comment]
We are currently using Scrutinizer to achieve this. Although there is no CI config stored in the repository, it will indeed run when commits are pushed and pull requests are opened. Scrutinizer is the source of the badges you see in `README.md`.
The Scrutinizer configuration runs the `mediact/testing-suite` package, with:

- Composer checks
- PHPCS
- PHPMD
- PHPStan
- Phpunit
- DependencyGuard

So Dependency Guard checks its own code in CI.

**Comment by willemstuursma** [comment]
OK because it is not configured here in a standardized way it was not clear to me. 

Could you add something like:

```bash
find src  tests -name '*.php' | xargs -n 1 -P4 /usr/bin/php -l
```

Or the scrutinizer equivalent.

**Comment by johmanx10** [comment]
Syntax errors are already covered by our configuration of GrumPHP. Granted, this will only show the first syntax error, because it breaks the test, but having `mediact/testing-suite` as dev-requirement should prevent you from committing files with syntax errors. I will add a test using the command you supplied, but only because that gives a more complete image while debugging issues.

**Comment by johmanx10** [comment]
I've added the test for syntax checks. Would you consider the issue closed with this change?

**Comment by johmanx10** [comment]
I've removed your suggested check again, because it gives false positives for syntax errors when running on PHP 7.1.6:

```
Fatal error: Syntax only allowed in Hack files (<?hh) or with -v Eval.EnableHipHopSyntax=true in src/Candidate/CandidateExtractor.php on line 56

Fatal error: Parameter $symbols is variadic and has a type constraint (Mediact\DependencyGuard\Php\SymbolInterface); variadic params with type constraints are not supported in non-Hack files in src/Php/SymbolIterator.php on line 19
```
The first error finds a nullable type declaration to be wrong, which is supported in `7.1`. The second error is self-explanatory. Syntax errors will always cause the test to break, so I will leave the specific syntax test out.
